### ISSUE TITLE
Alt+O (switch from header/source) keyboard shortcut not working with vscode-cpptools intellisense disabled

### ISSUE THREAD

**Issue by mobad** [cquery-project/vscode-cquery#48]
You get an error now:
`The command is disabled because "C_Cpp.intelliSenseEngine" is set to "Disabled".`

Now that we can [fully disable intellisense](https://github.com/Microsoft/vscode-cpptools/commit/3790fa95e707e78830d7c689258a7e7ec2f9e15b) in vscode-cpptools, are there plans to plans to duplicate some of these keyboard shortcuts in the cquery extension?

What are the recommended settings for vscode-cpptools now for people who want debugging from vscode-cpptools?
I've currently got:
    "C_Cpp.autocomplete": "Disabled",
    "C_Cpp.errorSquiggles": "Disabled",
    "C_Cpp.intelliSenseEngine": "Disabled",

**Comment by jacobdufault** [comment]
I use https://marketplace.visualstudio.com/items?itemName=ryzngard.vscode-header-source for this which is fast; some of the other extensions are slow for this since they query the project.

**Comment by jacobdufault** [comment]
Re recommended settings, I'm not sure, as I don't use vscode-cpptools.

**Comment by mobad** [comment]
@bdeeming With the suggested extension and "Disabled", Alt+O works.
You will also need to remove the Alt+O shortcut from vscode-cpptools or it will override this one.

@jacobdufault Recommended settings for debugging with vscode-cpptools would be useful to put in the wiki as I think this would be a very common setup.

**Comment by jacobdufault** [comment]
> @jacobdufault do you use an extension for debugger integration?

Not much, I've often have painful experiences with debuggers on Chrome; they are too slow or unreliable (chrome's test runner also runs a separate process for each test, etc, which makes it more difficult to integrate tooling with). I tried https://github.com/WebFreak001/code-debug for a bit but I was unable to get it working well enough; I've been meaning to try the microsoft cpp tools since others have told me it works pretty well.

> @jacobdufault Recommended settings for debugging with vscode-cpptools would be useful to put in the wiki as I think this would be a very common setup.

I'd greatly appreciate it if you're willing to edit the wiki :)
